name: git_notes
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1
  file_picker: ^8.0.6
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  page_transition: ^2.1.0
  flutter_vector_icons: ^2.0.0
  markdown_widget: ^2.3.2+6
  open_file_plus: ^3.4.1+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  protobuf: ^3.1.0
  shared_preferences: ^2.3.2
  rinf: ^6.15.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
