name: git_notes
description: "A Git based notes app... Currently is just a Git client for android."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.1-alpha

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_colorpicker: ^1.1.0
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1
  file_picker: ^8.0.6
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  flutter_vector_icons: ^2.0.0
  markdown: ^7.2.2
  open_file_plus: ^3.4.1+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  protobuf: ^3.1.0
  rinf: ^6.15.0
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.10.0
  animations: ^2.0.11
  url_launcher: ^6.3.1
  text_scroll: ^0.2.0
  markdown_editor_plus: ^0.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  
